# =====================================================================
# Map-Modules.ps1  --  regenerate the module map table in modules/README.md
#
#   The README carries a table of "how many lines does each module have" and
#   "where does it land in the assembled translation unit". Both numbers change
#   on *every* source edit, so the table is regenerated by a tool instead of
#   being maintained by hand - a stale map is a document that lies.
#
#   Rules mirrored from Verify-ModuleSplit.ps1:
#     * the unit is: shell header lines 1..(first include - 1), then the modules
#       in include order
#     * "lines" counts the newline bytes of each module
#     * the first module starts at the first include line number
#
#   The family column is read back from the existing table and preserved, so a
#   hand-written description is not lost. Numbers are written in Persian digits
#   to match the rest of the file.
#
#   NOTE ON ENCODING: this script is deliberately ASCII-only. Windows
#   PowerShell parses a .ps1 with no BOM as ANSI, so Persian literals inside the
#   script would be mangled at parse time. Persian digits and the en dash are
#   therefore built from code points, and the README itself is always read and
#   written with an explicit UTF-8 encoding.
#
#   Read-only except for modules/README.md.
# =====================================================================
param(
   [string]$Shell      = "D:/ICT_indicator/01_CANONICAL_CANDIDATES/ICT_Assistant_Canonical.mq5",
   [string]$ModulesDir = "",
   [string]$Readme     = ""
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Shell)) { throw "Shell not found: $Shell" }
if ([string]::IsNullOrWhiteSpace($ModulesDir)) { $ModulesDir = Join-Path (Split-Path -Parent $Shell) 'modules' }
if ([string]::IsNullOrWhiteSpace($Readme))     { $Readme     = Join-Path $ModulesDir 'README.md' }
if (-not (Test-Path -LiteralPath $Readme)) { throw "README not found: $Readme" }

$latin1 = [System.Text.Encoding]::GetEncoding(28591)
$shellLines = [System.IO.File]::ReadAllLines($Shell, $latin1)

$includeLines = @()
$includeNames = @()
for ($i = 0; $i -lt $shellLines.Length; $i++) {
   $m = [regex]::Match($shellLines[$i], '^\s*#include\s+"([^"]+)"\s*$')
   if ($m.Success) { $includeLines += ($i + 1); $includeNames += $m.Groups[1].Value }
}
if ($includeNames.Count -eq 0) { throw "No #include lines found in $Shell" }
$firstInc = $includeLines[0]

$faDigits = @([char]0x06F0, [char]0x06F1, [char]0x06F2, [char]0x06F3, [char]0x06F4,
              [char]0x06F5, [char]0x06F6, [char]0x06F7, [char]0x06F8, [char]0x06F9)
$enDash = [char]0x2013
$backtick = [char]0x0060

function ConvertTo-PersianDigits([string]$s) {
   $out = ''
   foreach ($c in $s.ToCharArray()) {
      if ($c -ge '0' -and $c -le '9') { $out += $faDigits[[int]$c - 48] } else { $out += $c }
   }
   return $out
}

# ---- family column, read back from the existing table (keyed by file name) ----
$readmeLines = [System.IO.File]::ReadAllLines($Readme, [System.Text.Encoding]::UTF8)
$family = @{}
$headerIdx = -1
$tableEnd  = -1
for ($i = 0; $i -lt $readmeLines.Length; $i++) {
   $t = $readmeLines[$i]
   if ($headerIdx -lt 0 -and $t.StartsWith('| # |')) { $headerIdx = $i; continue }
   if ($headerIdx -ge 0) {
      if ($t.StartsWith('|')) { $tableEnd = $i; continue }
      break
   }
}
if ($headerIdx -lt 0 -or $tableEnd -lt 0) { throw "Module map table not found in $Readme" }

$rowRe = '^\|\s*[^|]+\|\s*' + [regex]::Escape($backtick) + '([^' + [regex]::Escape($backtick) + ']+)' + [regex]::Escape($backtick) + '\s*\|[^|]*\|[^|]*\|\s*(.*?)\s*\|\s*$'
for ($i = $headerIdx; $i -le $tableEnd; $i++) {
   $m = [regex]::Match($readmeLines[$i], $rowRe)
   if ($m.Success) { $family[$m.Groups[1].Value] = $m.Groups[2].Value }
}

# ---- rows ----
$rows = New-Object 'System.Collections.Generic.List[string]'
$rows.Add('| # | ' + $readmeLines[$headerIdx].Split('|')[2].Trim() + ' | ' +
          $readmeLines[$headerIdx].Split('|')[3].Trim() + ' | ' +
          $readmeLines[$headerIdx].Split('|')[4].Trim() + ' | ' +
          $readmeLines[$headerIdx].Split('|')[5].Trim() + ' |')
$rows.Add($readmeLines[$headerIdx + 1])   # the |---| separator row, verbatim

$cursor = $firstInc
$total = 0
$idx = 0
foreach ($rel in $includeNames) {
   $leaf = Split-Path -Leaf $rel
   $p = Join-Path $ModulesDir $leaf
   if (-not (Test-Path -LiteralPath $p)) { throw "Module not found: $p" }
   $count = 0
   foreach ($b in [System.IO.File]::ReadAllBytes($p)) { if ($b -eq 10) { $count++ } }
   $start = $cursor
   $end   = $cursor + $count - 1
   $cursor = $end + 1
   $total += $count
   $idx++
   $num  = ConvertTo-PersianDigits ('{0:D2}' -f $idx)
   $cTxt = ConvertTo-PersianDigits ([string]$count)
   $rTxt = ConvertTo-PersianDigits (('{0}' -f $start) + $enDash + ('{0}' -f $end))
   $fam  = if ($family.ContainsKey($leaf)) { $family[$leaf] } else { '' }
   $rows.Add('| ' + $num + ' | ' + $backtick + $leaf + $backtick + ' | ' + $cTxt + ' | ' + $rTxt + ' | ' + $fam + ' |')
}

$newLines = New-Object 'System.Collections.Generic.List[string]'
for ($i = 0; $i -lt $headerIdx; $i++) { $newLines.Add($readmeLines[$i]) }
foreach ($r in $rows) { $newLines.Add($r) }
for ($i = $tableEnd + 1; $i -lt $readmeLines.Length; $i++) { $newLines.Add($readmeLines[$i]) }

[System.IO.File]::WriteAllLines($Readme, $newLines, (New-Object System.Text.UTF8Encoding($false)))

Write-Output ("modules   : {0}" -f $includeNames.Count)
Write-Output ("unit lines: {0} (first module at line {1}; modules total {2})" -f $cursor, $firstInc, $total)
Write-Output ("rewrote   : {0}" -f $Readme)
exit 0
